services:

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - /tmp/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    networks:
      - express-app

  app:
    build:
      context: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_NAME=app
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=postgres
    networks:
      - express-app

networks:
  express-app: